=== mmoris03/sew/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidadProxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="podio" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<!-- Tipo simple con restriccion para la longitud del circuito -->
	<xs:simpleType name="LongitudCircuitoConRestriccion">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="20000" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudCircuitoConRestriccion">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple con restriccion para la anchura del circuito -->
	<xs:simpleType name="AnchuraCircuitoConRestriccion">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="100" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="AnchuraCircuitoConRestriccion">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="numeroVueltas" type="xs:nonNegativeInteger" />
	<xs:element name="localidadProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nombre" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple con restriccion para la longitud -->
	<xs:simpleType name="LongitudConRestriccion">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-180.0" />
			<xs:maxInclusive value="180.0" />
		</xs:restriction>
	</xs:simpleType>
	<!-- Tipo simple con restriccion para la latitud -->
	<xs:simpleType name="LatitudConRestriccion">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>
	<!-- Tipo simple con restriccion para la altitud -->
	<xs:simpleType name="AltitudConRestriccion">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="5000" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudConRestriccion">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LatitudConRestriccion">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="AltitudConRestriccion">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:nonNegativeInteger" />
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="duracion" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="podio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo" type="xs:string" />
	<xs:element name="tercero" type="xs:string" />
</xs:schema>

=== mmoris03/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Circuit de Barcelona-Catalunya</nombre>
    <longitudCircuito unidades="metros">4657</longitudCircuito>
    <anchuraMedia unidades="metros">12</anchuraMedia>
    <fecha>2025-09-07</fecha>
    <hora>14:00:00</hora>
    <numeroVueltas>24</numeroVueltas>
    <localidadProxima>Montmeló</localidadProxima>
    <pais>España</pais>
    <patrocinador>Monster Energy</patrocinador>
    <referencias>
        <referencia nombre="Página oficial del Circuito de Barcelona-Catalunya">
            https://www.circuitcat.com/</referencia>
        <referencia nombre="Más información en Wikipedia">
            https://es.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya</referencia>
        <referencia nombre="Información del Circuito de Barcelona-Catalunya MotoGP">
            https://www.motogp.com/es/track/Barcelona</referencia>
    </referencias>
    <fotos>
        <foto alt="Vista aérea del Circuit de Barcelona-Catalunya"> multimedia/vista-aerea.jpg</foto>
        <foto alt="Piloto de MotoGP tomando una curva del Circuit de Barcelona-Catalunya">
            multimedia/piloto-curva.jpg</foto>
        <foto alt="Carrera de MotoGP en el Circuit de Barcelona-Catalunya con el público de fondo">
            multimedia/carrera-curva.jpg</foto>
    </fotos>
    <videos>
        <video alt="Vuelta al circuito de un piloto de Honda en 2015">multimedia/honda-onboard.mp4</video>
        <video alt="Recorrido narrado del circuito con una cámara GoPro">multimedia/gopro-lap.mp4</video>
    </videos>
    <!-- Inicio(1) -->
    <coordenadas>
        <longitud unidades="metros">2.261223741459883</longitud>
        <latitud unidades="grados">41.57002141925227</latitud>
        <altitud unidades="grados">119.9815022655145</altitud>
        <sector>1</sector>
    </coordenadas>
    <tramos>
        <!-- Inicio(1) -->
        <tramo>
            <distancia unidades="metros">686.22</distancia>
            <coordenadas>
                <longitud unidades="metros">2.261223741459883</longitud>
                <latitud unidades="grados">41.57002141925227</latitud>
                <altitud unidades="grados">119.9815022655145</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 2 -->
        <tramo>
            <distancia unidades="metros">28.88</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256836845695231</longitud>
                <latitud unidades="grados">41.56479577282675</latitud>
                <altitud unidades="grados">112.1009430922552</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 3 -->
        <tramo>
            <distancia unidades="metros">22.58</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256555135458453</longitud>
                <latitud unidades="grados">41.56464401810346</latitud>
                <altitud unidades="grados">111.9814031480789</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 4 -->
        <tramo>
            <distancia unidades="metros">29.44</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256283705296787</longitud>
                <latitud unidades="grados">41.56464297862309</latitud>
                <altitud unidades="grados">111.9522437291861</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 5 -->
        <tramo>
            <distancia unidades="metros">32.25</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255981003327416</longitud>
                <latitud unidades="grados">41.56478007673316</latitud>
                <altitud unidades="grados">112.2418890305771</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 6 -->
        <tramo>
            <distancia unidades="metros">29.31</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255621029447552</longitud>
                <latitud unidades="grados">41.56488704201879</latitud>
                <altitud unidades="grados">113.5085846353065</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 7 -->
        <tramo>
            <distancia unidades="metros">107.14</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25526996840038</longitud>
                <latitud unidades="grados">41.56486535663297</latitud>
                <altitud unidades="grados">114.1799869888623</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 8 -->
        <tramo>
            <distancia unidades="metros">67.33</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25421452950278</longitud>
                <latitud unidades="grados">41.56431477935144</latitud>
                <altitud unidades="grados">118.6271457008514</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 9 -->
        <tramo>
            <distancia unidades="metros">55.03</distancia>
            <coordenadas>
                <longitud unidades="metros">2.253423008865068</longitud>
                <latitud unidades="grados">41.56419187871545</latitud>
                <altitud unidades="grados">121.7702229979989</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 10 -->
        <tramo>
            <distancia unidades="metros">53.18</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252800734195874</longitud>
                <latitud unidades="grados">41.56435866648417</latitud>
                <altitud unidades="grados">123.6689387533272</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 11 -->
        <tramo>
            <distancia unidades="metros">56.96</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252382679092739</longitud>
                <latitud unidades="grados">41.56472015836391</latitud>
                <altitud unidades="grados">125.2332929918865</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 12 -->
        <tramo>
            <distancia unidades="metros">57.03</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252185047758342</longitud>
                <latitud unidades="grados">41.56521056474557</latitud>
                <altitud unidades="grados">126.113934030765</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 13 -->
        <tramo>
            <distancia unidades="metros">62.88</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252210379611497</longitud>
                <latitud unidades="grados">41.56572300668989</latitud>
                <altitud unidades="grados">127.0879007075736</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 14 -->
        <tramo>
            <distancia unidades="metros">257.21</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252432656683965</longitud>
                <latitud unidades="grados">41.56626349153305</latitud>
                <altitud unidades="grados">127.7273199233983</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 15 -->
        <tramo>
            <distancia unidades="metros">39.76</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254052957608916</longitud>
                <latitud unidades="grados">41.56823327576612</latitud>
                <altitud unidades="grados">130.9763803302394</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 16 -->
        <tramo>
            <distancia unidades="metros">39.12</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254456647162422</longitud>
                <latitud unidades="grados">41.56842453329151</latitud>
                <altitud unidades="grados">131.6617996581331</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 17 -->
        <tramo>
            <distancia unidades="metros">52.00</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254921724468089</longitud>
                <latitud unidades="grados">41.56837320802159</latitud>
                <altitud unidades="grados">132.4352756598984</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 18 -->
        <tramo>
            <distancia unidades="metros">44.13</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25534456250833</longitud>
                <latitud unidades="grados">41.56802885885098</latitud>
                <altitud unidades="grados">133.2900525802538</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 19 -->
        <tramo>
            <distancia unidades="metros">51.86</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255411398774871</longitud>
                <latitud unidades="grados">41.56763514363966</latitud>
                <altitud unidades="grados">133.1225828629581</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 20 -->
        <tramo>
            <distancia unidades="metros">182.77</distancia>
