=== mmoris03/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitudCircuito, anchuraMedia, fecha, hora, numeroVueltas, localidadProxima, pais, patrocinador, referencias, fotos, videos, coordenadas, tramos, vencedor, podio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitudCircuito (#PCDATA)>
<!ATTLIST longitudCircuito unidades CDATA #REQUIRED>
<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia unidades CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT localidadProxima (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia nombre CDATA #REQUIRED>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto alt CDATA #REQUIRED>
<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video alt CDATA #REQUIRED>
<!ELEMENT coordenadas (longitud, latitud, altitud, sector)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>
<!ATTLIST latitud unidades CDATA #REQUIRED>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ELEMENT sector (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT vencedor (#PCDATA)>
<!ATTLIST vencedor duracion CDATA #REQUIRED>
<!ELEMENT podio (primero, segundo, tercero)>
<!ELEMENT primero (#PCDATA)>
<!ELEMENT segundo (#PCDATA)>
<!ELEMENT tercero (#PCDATA)>

=== mmoris03/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Circuit de Barcelona-Catalunya</nombre>
    <longitudCircuito unidades="metros">4657</longitudCircuito>
    <anchuraMedia unidades="metros">12</anchuraMedia>
    <fecha>2025-09-07</fecha>
    <hora>14:00:00</hora>
    <numeroVueltas>24</numeroVueltas>
    <localidadProxima>Montmeló</localidadProxima>
    <pais>España</pais>
    <patrocinador>Monster Energy</patrocinador>
    <referencias>
        <referencia nombre="Página oficial del Circuito de Barcelona-Catalunya">
            https://www.circuitcat.com/</referencia>
        <referencia nombre="Más información en Wikipedia">
            https://es.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya</referencia>
        <referencia nombre="Información del Circuito de Barcelona-Catalunya MotoGP">
            https://www.motogp.com/es/track/Barcelona</referencia>
    </referencias>
    <fotos>
        <foto alt="Vista aérea del Circuit de Barcelona-Catalunya"> multimedia/vista-aerea.jpg</foto>
        <foto alt="Piloto de MotoGP tomando una curva del Circuit de Barcelona-Catalunya">
            multimedia/piloto-curva.jpg</foto>
        <foto alt="Carrera de MotoGP en el Circuit de Barcelona-Catalunya con el público de fondo">
            multimedia/carrera-curva.jpg</foto>
    </fotos>
    <videos>
        <video alt="Vuelta al circuito de un piloto de Honda en 2015">multimedia/honda-onboard.mp4</video>
        <video alt="Recorrido narrado del circuito con una cámara GoPro">multimedia/gopro-lap.mp4</video>
    </videos>
    <!-- Inicio(1) -->
    <coordenadas>
        <longitud unidades="metros">2.261223741459883</longitud>
        <latitud unidades="grados">41.57002141925227</latitud>
        <altitud unidades="grados">119.9815022655145</altitud>
        <sector>1</sector>
    </coordenadas>
    <tramos>
        <!-- Inicio(1) -->
        <tramo>
            <distancia unidades="metros">686.22</distancia>
            <coordenadas>
                <longitud unidades="metros">2.261223741459883</longitud>
                <latitud unidades="grados">41.57002141925227</latitud>
                <altitud unidades="grados">119.9815022655145</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 2 -->
        <tramo>
            <distancia unidades="metros">28.88</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256836845695231</longitud>
                <latitud unidades="grados">41.56479577282675</latitud>
                <altitud unidades="grados">112.1009430922552</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 3 -->
        <tramo>
            <distancia unidades="metros">22.58</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256555135458453</longitud>
                <latitud unidades="grados">41.56464401810346</latitud>
                <altitud unidades="grados">111.9814031480789</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 4 -->
        <tramo>
            <distancia unidades="metros">29.44</distancia>
            <coordenadas>
                <longitud unidades="metros">2.256283705296787</longitud>
                <latitud unidades="grados">41.56464297862309</latitud>
                <altitud unidades="grados">111.9522437291861</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 5 -->
        <tramo>
            <distancia unidades="metros">32.25</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255981003327416</longitud>
                <latitud unidades="grados">41.56478007673316</latitud>
                <altitud unidades="grados">112.2418890305771</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 6 -->
        <tramo>
            <distancia unidades="metros">29.31</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255621029447552</longitud>
                <latitud unidades="grados">41.56488704201879</latitud>
                <altitud unidades="grados">113.5085846353065</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 7 -->
        <tramo>
            <distancia unidades="metros">107.14</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25526996840038</longitud>
                <latitud unidades="grados">41.56486535663297</latitud>
                <altitud unidades="grados">114.1799869888623</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 8 -->
        <tramo>
            <distancia unidades="metros">67.33</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25421452950278</longitud>
                <latitud unidades="grados">41.56431477935144</latitud>
                <altitud unidades="grados">118.6271457008514</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 9 -->
        <tramo>
            <distancia unidades="metros">55.03</distancia>
            <coordenadas>
                <longitud unidades="metros">2.253423008865068</longitud>
                <latitud unidades="grados">41.56419187871545</latitud>
                <altitud unidades="grados">121.7702229979989</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 10 -->
        <tramo>
            <distancia unidades="metros">53.18</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252800734195874</longitud>
                <latitud unidades="grados">41.56435866648417</latitud>
                <altitud unidades="grados">123.6689387533272</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 11 -->
        <tramo>
            <distancia unidades="metros">56.96</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252382679092739</longitud>
                <latitud unidades="grados">41.56472015836391</latitud>
                <altitud unidades="grados">125.2332929918865</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 12 -->
        <tramo>
            <distancia unidades="metros">57.03</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252185047758342</longitud>
                <latitud unidades="grados">41.56521056474557</latitud>
                <altitud unidades="grados">126.113934030765</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 13 -->
        <tramo>
            <distancia unidades="metros">62.88</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252210379611497</longitud>
                <latitud unidades="grados">41.56572300668989</latitud>
                <altitud unidades="grados">127.0879007075736</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 14 -->
        <tramo>
            <distancia unidades="metros">257.21</distancia>
            <coordenadas>
                <longitud unidades="metros">2.252432656683965</longitud>
                <latitud unidades="grados">41.56626349153305</latitud>
                <altitud unidades="grados">127.7273199233983</altitud>
                <sector>1</sector>
            </coordenadas>
        </tramo>
        <!-- 15 -->
        <tramo>
            <distancia unidades="metros">39.76</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254052957608916</longitud>
                <latitud unidades="grados">41.56823327576612</latitud>
                <altitud unidades="grados">130.9763803302394</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 16 -->
        <tramo>
            <distancia unidades="metros">39.12</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254456647162422</longitud>
                <latitud unidades="grados">41.56842453329151</latitud>
                <altitud unidades="grados">131.6617996581331</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 17 -->
        <tramo>
            <distancia unidades="metros">52.00</distancia>
            <coordenadas>
                <longitud unidades="metros">2.254921724468089</longitud>
                <latitud unidades="grados">41.56837320802159</latitud>
                <altitud unidades="grados">132.4352756598984</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 18 -->
        <tramo>
            <distancia unidades="metros">44.13</distancia>
            <coordenadas>
                <longitud unidades="metros">2.25534456250833</longitud>
                <latitud unidades="grados">41.56802885885098</latitud>
                <altitud unidades="grados">133.2900525802538</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 19 -->
        <tramo>
            <distancia unidades="metros">51.86</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255411398774871</longitud>
                <latitud unidades="grados">41.56763514363966</latitud>
                <altitud unidades="grados">133.1225828629581</altitud>
                <sector>2</sector>
            </coordenadas>
        </tramo>
        <!-- 20 -->
        <tramo>
            <distancia unidades="metros">182.77</distancia>
            <coordenadas>
                <longitud unidades="metros">2.255237627835973</longitud>
